repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: PY Linter
        entry: ruff check
        language: system
        types: [python]
        pass_filenames: false

      - id: ty-check
        name: PY Type Check
        entry: ty check
        language: system
        types: [python]
        pass_filenames: false

      - id: eslint
        name: TS Linter
        entry: yarn lint
        language: system
        pass_filenames: true

      - id: ruff-format
        name: PY Formatter
        entry: ruff format
        language: system
        types: [python]
        pass_filenames: true

      # - id: prettier
      #   name: TS Format
      #   entry: yarn format
      #   language: system
      #   pass_filenames: false
      #   always_run: true
